title: <p align="center"> Sahel Eskandar </p> # your name (or website title) here

logo: "/images/logo.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sahel-eskandar/">LinkedIn</a> |
  <a href="https://github.com/Sahel-Eskandar">GitHub</a>
  </p>
  <p align="justify">
  Data Scientist | ML Engineer | PhD 
  <br><br>
  Machine Learning Scientist with 6+ yrs. of blended industrial and academic experience. More than 10+ yrs. of data and statistical analysis. Problem solver, seeking a challenging environment and problems to solve and grow within a team.
  <br><br>
  </p>
  </p>
  </p>
  </p>
  </p>
  </p>
  </p>
  </p>
  </p>
  </p>

  
theme: jekyll-theme-minimal
google_analytics: G-BQ0S7YH5RV # your Google Analytics tracking ID here
